# Generated by Django 5.2 on 2025-05-01 07:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usage_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ご使用番号"
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="部屋番号"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="氏名")),
                (
                    "address",
                    models.CharField(blank=True, max_length=200, verbose_name="住所"),
                ),
                (
                    "has_service",
                    models.BooleanField(default=False, verbose_name="開栓中か"),
                ),
                (
                    "meter_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="メーター番号"
                    ),
                ),
                (
                    "meter_model",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="メーター型式"
                    ),
                ),
                (
                    "retailer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="小売事業者"
                    ),
                ),
            ],
            options={
                "verbose_name": "顧客",
                "verbose_name_plural": "顧客一覧",
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("code", models.CharField(max_length=7, unique=True)),
                ("company", models.CharField(blank=True, max_length=50)),
                ("district", models.CharField(blank=True, max_length=50)),
                ("team", models.CharField(blank=True, max_length=50)),
                ("group", models.CharField(blank=True, max_length=50)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="customuser_set",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="customuser_set",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meter_status",
                    models.CharField(
                        blank=True,
                        choices=[("取付", "取付"), ("取外", "取外")],
                        max_length=10,
                        verbose_name="メーター状況",
                    ),
                ),
                (
                    "mvalve_status",
                    models.CharField(
                        blank=True,
                        choices=[("開", "開"), ("閉", "閉")],
                        max_length=10,
                        verbose_name="M栓状況",
                    ),
                ),
                (
                    "opening_round",
                    models.CharField(
                        choices=[
                            ("開栓済み", "開栓済み"),
                            ("開栓未実施", "開栓未実施"),
                        ],
                        default="開栓未実施",
                        max_length=20,
                        verbose_name="開栓巡目",
                    ),
                ),
                (
                    "presence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("未訪問", "未訪問"),
                            ("在宅", "在宅"),
                            ("不在", "不在"),
                        ],
                        max_length=10,
                        verbose_name="在宅状況",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="担当者",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.customer",
                        verbose_name="顧客",
                    ),
                ),
            ],
            options={
                "verbose_name": "割当",
                "verbose_name_plural": "割当一覧",
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("施工前", "施工前"),
                            ("ユニオン錆確認", "ユニオン錆確認"),
                            ("パッキン取付", "パッキン取付"),
                            ("M取付", "M取付"),
                            ("パージ前", "パージ前"),
                            ("パージ後", "パージ後"),
                            ("チャートor5分指針", "チャートor5分指針"),
                            ("保安閉栓", "保安閉栓"),
                            ("M栓開+メーター", "M栓開+メーター"),
                            ("その他", "その他"),
                        ],
                        max_length=20,
                        verbose_name="写真種別",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="photos/%Y/%m/%d/", verbose_name="画像"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="撮影日時"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.assignment",
                        verbose_name="割当",
                    ),
                ),
            ],
            options={
                "verbose_name": "写真",
                "verbose_name_plural": "写真一覧",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="案件名")),
                ("date", models.DateField(auto_now_add=True, verbose_name="作成日")),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="アクセス許可ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件",
                "verbose_name_plural": "案件一覧",
            },
        ),
        migrations.AddField(
            model_name="assignment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="core.project",
                verbose_name="案件",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignment",
            unique_together={("project", "customer")},
        ),
    ]
