# Generated by Django 5.2 on 2025-05-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "ユーザー", "verbose_name_plural": "ユーザー一覧"},
        ),
        migrations.AlterField(
            model_name="assignment",
            name="presence",
            field=models.CharField(
                blank=True,
                choices=[("未訪問", "未訪問"), ("在宅", "在宅"), ("不在", "不在")],
                default="未訪問",
                max_length=10,
                verbose_name="在宅状況",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="code",
            field=models.CharField(
                max_length=7, unique=True, verbose_name="氏名コード"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="company",
            field=models.CharField(blank=True, max_length=50, verbose_name="会社"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="district",
            field=models.CharField(blank=True, max_length=50, verbose_name="地区"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="group",
            field=models.CharField(blank=True, max_length=50, verbose_name="グループ"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="customuser_set",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="team",
            field=models.CharField(blank=True, max_length=50, verbose_name="チーム"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="customuser_set",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
