# Generated by Django 5.2 on 2025-05-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_customuser_options_alter_assignment_presence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="opening_round",
            field=models.CharField(
                choices=[
                    ("開栓済み", "開栓済み"),
                    ("開栓作業中", "開栓作業中"),
                    ("開栓未実施", "開栓未実施"),
                ],
                default="開栓未実施",
                max_length=20,
                verbose_name="開栓巡目",
            ),
        ),
    ]
