# Generated by Django 5.2 on 2025-05-05 03:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_assignment_opening_round"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="meter_status",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="mvalve_status",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="opening_round",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="presence",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="has_service",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="meter_model",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="meter_number",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="retailer",
        ),
        migrations.AddField(
            model_name="assignment",
            name="absence_action",
            field=models.CharField(
                blank=True,
                choices=[("開栓", "開栓"), ("保安閉栓", "保安閉栓")],
                default="開栓",
                max_length=10,
                verbose_name="不在時処置",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="checked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="チェック日時"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="checked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checked_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="チェックユーザー",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="gauge_spec",
            field=models.CharField(
                blank=True,
                choices=[
                    ("不要", "不要"),
                    ("供給圧", "供給圧"),
                    ("テスト圧", "テスト圧"),
                ],
                default="不要",
                max_length=10,
                verbose_name="ゲージ仕様",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="leaflet_status",
            field=models.CharField(
                blank=True,
                choices=[("未投函", "未投函"), ("投函済", "投函済")],
                max_length=10,
                null=True,
                verbose_name="投函ステータス",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="leaflet_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("不要", "不要"),
                    ("修", "修"),
                    ("F", "F"),
                    ("その他", "その他"),
                ],
                default="不要",
                max_length=10,
                verbose_name="投函用紙種別",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="m_valve_attach",
            field=models.CharField(
                blank=True,
                choices=[("取付", "取付"), ("取外", "取外")],
                default="取付",
                max_length=10,
                verbose_name="M取付外",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="m_valve_state",
            field=models.CharField(
                blank=True,
                choices=[("アキ", "アキ"), ("シマリ", "シマリ")],
                max_length=10,
                verbose_name="M栓状態",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="open_round",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1巡目"),
                    (2, "2巡目"),
                    (3, "3巡目"),
                    (4, "4巡目"),
                    (5, "5巡目"),
                ],
                default=1,
                verbose_name="開栓巡目",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="open_status",
            field=models.CharField(
                choices=[
                    ("未訪問", "未訪問"),
                    ("作業中", "開栓作業中"),
                    ("未実施", "開栓未実施"),
                    ("完了", "開栓完了"),
                    ("最終チェック完了", "最終チェック完了"),
                ],
                default="未訪問",
                max_length=20,
                verbose_name="開栓状況",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="performed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="実施日時"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="実施ユーザー",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="pr_status",
            field=models.CharField(
                choices=[("未訪問", "未訪問"), ("在宅", "在宅"), ("不在", "不在")],
                default="未訪問",
                max_length=10,
                verbose_name="PR状況",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="sequence",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="プロジェクト内での通し番号（後ほど自動採番）",
                null=True,
                verbose_name="通し番号",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="building_name",
            field=models.CharField(
                blank=True,
                help_text="将来の建物名管理用",
                max_length=50,
                verbose_name="集合住宅名",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="district",
            field=models.CharField(
                blank=True,
                help_text="作成者の所属地区が自動セットされます",
                max_length=50,
                verbose_name="地区",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_completed",
            field=models.BooleanField(
                default=False,
                help_text="スタッフが対応完了後にチェックします",
                verbose_name="完了サイン",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="order_no",
            field=models.CharField(
                blank=True,
                help_text="大文字1字＋数字5桁（例：A01234）",
                max_length=6,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="オーダーNo.は大文字1字＋数字5桁（例：A01234）で入力してください。",
                        regex="^[A-Z][0-9]{5}$",
                    )
                ],
                verbose_name="オーダーNo.",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(blank=True, max_length=20, verbose_name="氏名"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="usage_no",
            field=models.CharField(
                max_length=4,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="ご使用番号は必ず4桁の数字で指定してください。",
                        regex="^\\d{4}$",
                    )
                ],
                verbose_name="ご使用番号",
            ),
        ),
    ]
