# Generated by Django 5.2 on 2025-05-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_assignment_assigned_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="block_number",
            field=models.CharField(blank=True, max_length=10, verbose_name="丁番号"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="building_number",
            field=models.CharField(blank=True, max_length=10, verbose_name="棟番号"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="meter_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="メーター番号"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="meter_type",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="メーター種別"
            ),
        ),
    ]
