# Generated by Django 5.1.2 on 2025-05-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_assignment_block_number_assignment_building_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="削除予定日時"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="削除フラグ"),
        ),
    ]
