# Generated by Django 5.2 on 2025-05-09 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_create_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='order_no',
            field=models.CharField(blank=True, help_text='大文字1字＋数字5桁（例：A01234）', max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='オーダーNo.は大文字1字＋数字5桁（例：A01234）で入力してください。', regex='^[A-Z][0-9]{5}$')], verbose_name='オーダーNo.'),
        ),
    ]
