# Generated by Django 5.2 on 2025-05-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_project_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='absence_action',
            field=models.CharField(blank=True, choices=[('open', '開栓'), ('safety', '保安閉栓')], default='open', max_length=20, verbose_name='不在時処置'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='block_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='丁番号'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='building_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='棟番号'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='gauge_spec',
            field=models.CharField(blank=True, choices=[('none', '不要'), ('supply', '供給圧'), ('test', 'テスト圧')], default='none', max_length=10, verbose_name='ゲージ仕様'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='leaflet_status',
            field=models.CharField(blank=True, choices=[('not_posted', '未投函'), ('posted', '投函済')], max_length=20, null=True, verbose_name='投函ステータス'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='leaflet_type',
            field=models.CharField(blank=True, choices=[('none', '不要'), ('shu', '修'), ('f', 'F'), ('other', 'その他')], default='none', max_length=10, verbose_name='投函用紙種別'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='m_valve_attach',
            field=models.CharField(blank=True, choices=[('attached', '取付'), ('detached', '取外')], default='attached', max_length=10, verbose_name='M取付外'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='m_valve_state',
            field=models.CharField(blank=True, choices=[('closed', 'シマリ'), ('open', 'アキ')], max_length=10, verbose_name='M栓状態'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='meter_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='メーター番号'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='meter_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='メーター種別'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='open_status',
            field=models.CharField(choices=[('not_visited', '未訪問'), ('in_progress', '開栓作業中'), ('not_done', '開栓未実施'), ('completed', '開栓完了'), ('final_checked', '最終チェック完了')], default='not_visited', max_length=20, verbose_name='開栓状況'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='pr_status',
            field=models.CharField(choices=[('not_visited', '未訪問'), ('home', '在宅'), ('absent', '不在')], default='not_visited', max_length=20, verbose_name='PR状況'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('before', '施工前'), ('union_rust', 'ユニオン錆確認'), ('packing', 'パッキン取付'), ('m_attach', 'M取付'), ('pre_purge', 'パージ前'), ('post_purge', 'パージ後'), ('chart', 'チャートor5分指針'), ('safety_close', '保安閉栓'), ('m_open_meter', 'M栓開+メーター'), ('other', 'その他')], max_length=20, verbose_name='写真種別'),
        ),
    ]
